Add html and css files
ViraRiefertDev/gitProjectCounter pull request #2
Opened 2024-10-09 18:50 UTC by PaulPufel

2024-10-09 19:58 UTC, ViraRiefertDev requested changes

2024-10-09 19:58 UTC, ViraRiefertDev commented on styles.css
> +body {
на боди flex лучше не навешивать, для этого я и создала root контейнер, чтобы его сделать флексом и он был как бы обёрткой нашего всего сайта

2024-10-09 19:58 UTC, ViraRiefertDev commented on styles.css
> +#counterResult {
id  в стилях тоже лучше не использовать, есть такое правило класы для стилей, id для логики (тоесть js). Тоесть для div с айдишником counterResult лучше в HTML добавить еще и класс и с ним уже в стилях работать

2024-10-09 19:58 UTC, ViraRiefertDev commented on styles.css
> +body {
тем более ты навесил не только на боди флексконтейнер, но и на тег html

2024-10-09 20:18 UTC, PaulPufel commented
Привет Вера!

Тоже не спишь. Замечания я твои понял.

Как правило мне их надо исправить и опять в ГИТ как раньше через add, commit и push отправить?

Так как моя ветка уже создана. И в неё всё автоматически запушится.

Срасибо тебе за помощь.

И спокойной ночи. До завтра.

 

Mit Grüß Paul

 

 
 

Gesendet: Mittwoch, 09. Oktober 2024 um 21:58 Uhr
Von: "ViraRiefertDev" ***@***.***>
An: "ViraRiefertDev/gitProjectCounter" ***@***.***>
Cc: "PaulPufel" ***@***.***>, "Author" ***@***.***>
Betreff: Re: [ViraRiefertDev/gitProjectCounter] Add html and css files (PR #2)


 

@ViraRiefertDev requested changes on this pull request.


In styles.css:

> @@ -0,0 +1,55 @@
+* {
+    box-sizing: border-box;
+}
+html,
+body {


на боди flex лучше не навешивать, для этого я и создала root контейнер, чтобы его сделать флексом и он был как бы обёрткой нашего всего сайта


In styles.css:

> +    width: 270px;
+    height: 300px;
+    text-align: center;
+    background-color: rgb(139, 241, 236);
+    padding: 20px;
+    border-radius: 10px;
+    box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
+}
+
+h1 {
+    font-size: 40px;
+    color: black;
+    margin-bottom: 20px;
+}
+
+#counterResult {


id в стилях тоже лучше не использовать, есть такое правило класы для стилей, id для логики (тоесть js). Тоесть для div с айдишником counterResult лучше в HTML добавить еще и класс и с ним уже в стилях работать


In styles.css:

> @@ -0,0 +1,55 @@
+* {
+    box-sizing: border-box;
+}
+html,
+body {


тем более ты навесил не только на боди флексконтейнер, но и на тег html

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2024-10-11 17:24 UTC, ViraRiefertDev approved these changes

2024-10-11 17:25 UTC, merged